version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - voting-net

  voting-backend:
    build: ./voting-backend
    container_name: voting-backend
    ports:
      - "5000:5000"
    depends_on:
      - redis
    networks:
      - voting-net

  voting-frontend:
    build: ./voting-frontend
    container_name: voting-frontend
    ports:
      - "80:80"
    depends_on:
      - voting-backend
    networks:
      - voting-net

networks:
  voting-net:
    driver: bridge
